### ISSUE TITLE
GraphQL Test Not working

### ISSUE THREAD

**Issue by cruzeMc** [graphql-java-kickstart/graphql-spring-boot#136]
package com.jncb.customerService.controller.resolvers;

import com.graphql.spring.boot.test.GraphQLResponse;
import com.graphql.spring.boot.test.GraphQLTest;
import com.graphql.spring.boot.test.GraphQLTestAutoConfiguration;
import com.graphql.spring.boot.test.GraphQLTestTemplate;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringRunner;

import java.io.IOException;

import static graphql.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

//@ContextConfiguration(classes = CustomerServiceApplication.class)
@GraphQLTest
@RunWith(SpringRunner.class)
public class QueryTest {
	@Autowired
	GraphQLTestAutoConfiguration graphQLTestAutoConfiguration;

	@Test
	public void simpleTest() {
		System.out.println("WORKING!");
	}

	@Test
	public void findCustomerSummaryByIDTest() throws IOException {
		GraphQLResponse response = graphQLTestAutoConfiguration.graphQLTestUtils().postForResource("customer-summary.graphqls");
		assertNotNull(response);
		assertTrue(response.isOk());
		System.out.println(response.getRawResponse().getBody());
	}
}

java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:226)
	at sun.reflect.annotation.AnnotationParser.parseAnnotationArray(AnnotationParser.java:765)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:537)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at java.lang.reflect.Method.getDefaultValue(Method.java:606)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:132)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:149)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:46)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by eljog** [comment]
@cruzeMc did you find a solution?
I am also in the same boat. Even if my test methods are empty, it throws this exception when I add @GraphQLTest annotation. The same test class would run fine if I do not add this annotation.

**Comment by oliemansm** [comment]
@cruzeMc @eljog Can either of you share a small but complete test to reproduce this. Because my own tests are succeeding.

**Comment by oliemansm** [comment]
Made some improvements to the test auto configuration when using `@GraphQLTest` or `@SpringBootTest`. Unit tests within the project using both run correctly.
