### ISSUE TITLE
How to map MethodFieldResolver-Exceptions to Response

### ISSUE THREAD

**Issue by LarsKoelpin** [graphql-java-kickstart/graphql-spring-boot#285]
Hey there.

Lets say I have a Graphql mutation
`mutation CreateUser(name: String) {... on User {} ... on InvalidName {}}`

which shall create a user and is backed by the following resolver:
`class Resolver {
    fun createUser(user: Name) {
        ...
    }
}`

You'll notice it takes a Name and not a String, so the Name class would look like this:
```kotlin 
class Name(@get:JsonValue val value: String) {
    init {
        if(value.length < 3) {
            throw IllegalArgumentException("Name shall have a minimum of 3 characters")
        }
    }
}
```

If the Name is not valid, 
`mutation CreateUser(name: "a") // a is not valid`
it throws an Exception like expected.
```kotlin

java.lang.IllegalArgumentException: Cannot construct instance of `org.Name`, problem: Name shall have a minimum of 3 characters
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.user["email"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3678) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.coxautodev.graphql.tools.MethodFieldResolver$createDataFetcher$$inlined$forEachIndexed$lambda$1.invoke(MethodFieldResolver.kt:88) ~[graphql-java-tools-5.6.1.jar:na]
	at com.coxautodev.graphql.tools.MethodFieldResolver$createDataFetcher$$inlined$forEachIndexed$lambda$1.invoke(MethodFieldResolver.kt:23) ~[graphql-java-tools-5.6.1.jar:na]
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:160) ~[graphql-java-tools-5.6.1.jar:na]
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-13.0.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) [graphql-java-13.0.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) [graphql-java-13.0.jar:na]
```

Is it possible to hook a middleware in the parsing process, so I can map the Exception to a appropriate data Response, which in this case is an InvalidName (not to the errors field) and looks exactly like this?

```graphql
mutation CreateUser(name: "a") {
  ... on User {} 
  ... on InvalidName {}
}
```

Thanks

**Comment by LarsKoelpin** [comment]
Figured it out by myself.
I implemented my own Executor strategy based on https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/AsyncExecutionStrategy.java
