### ISSUE TITLE
Could not use application/stream+json Accept header on graphql query

### ISSUE THREAD

**Issue by overmike** [graphql-java-kickstart/graphql-spring-boot#424]
**Describe the bug**
I follow mostly guide in https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/ and change to use webflux starter

                 <dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-kickstart-spring-boot-starter-webflux</artifactId>
			<version>${graphql-spring-boot-starter.version}</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-kickstart-spring-boot-starter-tools</artifactId>
			<version>${graphql-spring-boot-starter.version}</version>
		</dependency>

I am able to query with no accept type specified

             curl \
                 -X POST \
                 -H "Content-Type: application/json" \
                --data '{ "query": "{ bookById(id:\"book-1\") { name } }" }' \
               http://localhost:9999/graphql
               {"data":{"bookById":{"name":"Harry Potter and the Philosopher's Stone"}}}

but fail with 406 NOT_ACCEPTABLE error when I specify accept type

                curl \
                 -X POST \
                 -H "Content-Type: application/json" -H "Accept: application/stream+json"\
                --data '{ "query": "{ bookById(id:\"book-1\") { name } }" }' \
               http://localhost:9999/graphql
               {"timestamp":"2020-06-18T05:59:14.477+00:00","path":"/graphql","status":406,"error":"Not Acceptable","message":"Could not find acceptable representation".....

No Idea if this is expected or anything wrong in my setup

**Exception**

org.springframework.web.server.NotAcceptableStatusException: 406 NOT_ACCEPTABLE "Could not find acceptable representation"

	at org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:191)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	|_ checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:191)
		at org.springframework.web.reactive.result.method.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:340)
		at org.springframework.web.reactive.result.method.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:288)
		at org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:96)
		at org.springframework.web.reactive.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:181)
		at org.springframework.web.reactive.DispatcherHandler.lambda$handle$0(DispatcherHandler.java:143)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:367)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:211)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4219)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: curl

**Comment by overmike** [comment]
Seem like the default support content type is only `application/json` if that is the case, this cache everything in the server. should I use the subscription feature instead of normal query

        2020-06-18 14:06:20.627 DEBUG 28339 --- [ctor-http-nio-7] o.s.w.s.adapter.HttpWebHandlerAdapter    : [6b321566-33] HTTP POST "/graphql"
        2020-06-18 14:06:20.627 DEBUG 28339 --- [ctor-http-nio-7] s.w.r.r.m.a.RequestMappingHandlerMapping : [6b321566-33] Mapped to graphql.kickstart.spring.webflux.GraphQLController#graphqlPOST(MediaType, String, String, String, String, ServerWebExchange)
        2020-06-18 14:06:20.628 DEBUG 28339 --- [ctor-http-nio-7] .r.m.a.RequestBodyMethodArgumentResolver : [6b321566-33] Content-Type:application/json
        2020-06-18 14:06:20.628 DEBUG 28339 --- [ctor-http-nio-7] .r.m.a.RequestBodyMethodArgumentResolver : [6b321566-33] 0..1 [java.lang.String]
        2020-06-18 14:06:20.628 DEBUG 28339 --- [ctor-http-nio-7] o.s.core.codec.StringDecoder             : [6b321566-33] Decoded "{ "query": "{ bookById(id:\"book-1\") { name } }" }"
        2020-06-18 14:06:20.630 DEBUG 28339 --- [ctor-http-nio-7] o.s.w.r.r.m.a.ResponseBodyResultHandler  : Using 'application/json' given [*/*] and supported [application/json]
        2020-06-18 14:06:20.630 DEBUG 28339 --- [ctor-http-nio-7] o.s.w.r.r.m.a.ResponseBodyResultHandler  : [6b321566-33] 0..1 [java.lang.Object]
        2020-06-18 14:06:20.630 DEBUG 28339 --- [ctor-http-nio-7] o.s.http.codec.json.Jackson2JsonEncoder  : [6b321566-33] Encoding [{data={bookById={name=Harry Potter and the Philosopher's Stone}}}]
        2020-06-18 14:06:20.630 DEBUG 28339 --- [ctor-http-nio-7] o.s.w.s.adapter.HttpWebHandlerAdapter    : [6b321566-33] Completed 200 OK
