### ISSUE TITLE
Parsing Input object for mutation through NPE when using graphql annotation. 

### ISSUE THREAD

**Issue by snowoutioua** [graphql-java-kickstart/graphql-spring-boot#657]
**Describe the bug**
Using annotation, define Mutation Resolver with a method that accept a bean object as input. Calling the mutation throw NPE.
`MethodDataFetcher`  couldn't construct the input object.

**To Reproduce**
I noticed the issue in my own application, but I clone the sample example and I [`graphql-annotation` ](https://github.com/graphql-java-kickstart/samples/tree/master/graphql-annotations) project and I noticed the same issue.

Start graphql-annotation project, call `CreatePerson` mutation (can use graphiql)
```
mutation createPerson($person: InputCreatePerson!) {
  createPerson(arg0: $person) {
    firstName
    lastName
    dateOfBirth
    id
  }
}

{
  "person": {
  	"firstName": "firstName",
    "lastName": "lastName"
  }
}

````
exception
```
2021-06-29 22:08:40.855  WARN 21718 --- [ graphql-exec-3] n.g.e.SimpleDataFetcherExceptionHandler  : Exception while fetching data (/createPerson) : null

java.lang.NullPointerException: null
        at graphql.annotations.dataFetchers.MethodDataFetcher.buildArg(MethodDataFetcher.java:140) ~[graphql-java-annotations-8.3.jar:na]
        at graphql.annotations.dataFetchers.MethodDataFetcher.invocationArgs(MethodDataFetcher.java:114) ~[graphql-java-annotations-8.3.jar:na]
        at graphql.annotations.dataFetchers.MethodDataFetcher.get(MethodDataFetcher.java:71) ~[graphql-java-annotations-8.3.jar:na]
        at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-16.2.jar:na]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-16.2.jar:na]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) ~[graphql-java-16.2.jar:na]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:177) ~[graphql-java-16.2.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Async.eachSequentiallyImpl(Async.java:80) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Async.eachSequentially(Async.java:69) ~[graphql-java-16.2.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Execution.executeOperation(Execution.java:165) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Execution.execute(Execution.java:104) ~[graphql-java-16.2.jar:na]
        at graphql.GraphQL.execute(GraphQL.java:557) ~[graphql-java-16.2.jar:na]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482) ~[graphql-java-16.2.jar:na]
        at graphql.GraphQL.executeAsync(GraphQL.java:446) ~[graphql-java-16.2.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.executeAsync(GraphQLInvoker.java:37) ~[graphql-java-kickstart-11.2.0-SNAPSHOT.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.execute(GraphQLInvoker.java:28) ~[graphql-java-kickstart-11.2.0-SNAPSHOT.jar:na]
        at graphql.kickstart.servlet.HttpRequestInvokerImpl.invoke(HttpRequestInvokerImpl.java:161) ~[graphql-java-servlet-11.2.0-SNAPSHOT.jar:na]
        at graphql.kickstart.servlet.HttpRequestInvokerImpl.lambda$invokeAndHandleAsync$2(HttpRequestInvokerImpl.java:79) ~[graphql-java-servlet-11.2.0-SNAPSHOT.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]

2021-06-29 22:08:40.876 ERROR 21718 --- [ graphql-exec-3] g.k.e.error.DefaultGraphQLErrorHandler   : Error executing query Exception while fetching data (/createPerson) : null

java.lang.NullPointerException: null
        at graphql.annotations.dataFetchers.MethodDataFetcher.buildArg(MethodDataFetcher.java:140) ~[graphql-java-annotations-8.3.jar:na]
        at graphql.annotations.dataFetchers.MethodDataFetcher.invocationArgs(MethodDataFetcher.java:114) ~[graphql-java-annotations-8.3.jar:na]
        at graphql.annotations.dataFetchers.MethodDataFetcher.get(MethodDataFetcher.java:71) ~[graphql-java-annotations-8.3.jar:na]
        at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-16.2.jar:na]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-16.2.jar:na]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) ~[graphql-java-16.2.jar:na]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:177) ~[graphql-java-16.2.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Async.eachSequentiallyImpl(Async.java:80) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Async.eachSequentially(Async.java:69) ~[graphql-java-16.2.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Execution.executeOperation(Execution.java:165) ~[graphql-java-16.2.jar:na]
        at graphql.execution.Execution.execute(Execution.java:104) ~[graphql-java-16.2.jar:na]
        at graphql.GraphQL.execute(GraphQL.java:557) ~[graphql-java-16.2.jar:na]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482) ~[graphql-java-16.2.jar:na]
        at graphql.GraphQL.executeAsync(GraphQL.java:446) ~[graphql-java-16.2.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.executeAsync(GraphQLInvoker.java:37) ~[graphql-java-kickstart-11.2.0-SNAPSHOT.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.execute(GraphQLInvoker.java:28) ~[graphql-java-kickstart-11.2.0-SNAPSHOT.jar:na]
        at graphql.kickstart.servlet.HttpRequestInvokerImpl.invoke(HttpRequestInvokerImpl.java:161) ~[graphql-java-servlet-11.2.0-SNAPSHOT.jar:na]
        at graphql.kickstart.servlet.HttpRequestInvokerImpl.lambda$invokeAndHandleAsync$2(HttpRequestInvokerImpl.java:79) ~[graphql-java-servlet-11.2.0-SNAPSHOT.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]

```

Here what I get as error response through GraphiQl, with my application, because I add Exception Handler. It's the same issue as described above.
```
{
  "errors": [
    {
      "message": "Exception while fetching data (/register) : Cannot invoke \"graphql.schema.GraphQLInputObjectField.getType()\" because the return value of \"graphql.schema.GraphQLInputObjectType.getField(String)\" is null",
      "locations": [
        {
          "line": 26,
          "column": 3
        }
      ],
      "path": [
        "register"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": null
}
```

**Additional context**
I used 11.1.0 and 12.0.0-SNAPSHOT and it's the same issue.

**Comment by BlasiusSecundus** [comment]
Hi, thanks for reporting! I did some quick investigation, but I could not reproduce the issue  with the `graphql-annotations` sample project so far. The `createPerson` mutation works correctly. Note that  your mutation is _not_ correct. The correct one is:

```graphql
mutation createPerson($person: InputCreatePerson!) {
  createPerson(createPerson: $person) {
    firstName
    lastName
    dateOfBirth
    id
  }
}
```

Notice that the argument name is not `arg0` but `createPerson`. With that fix, the mutation works correctly, returning a new person.

If I use your variant, I get the correct GraphQL error message (no NPE):

```json
{
  "errors": [
    {
      "message": "Validation error of type MissingFieldArgument: Missing field argument createPerson @ 'createPerson'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    },
    {
      "message": "Validation error of type UnknownArgument: Unknown field argument arg0 @ 'createPerson'",
      "locations": [
        {
          "line": 2,
          "column": 16
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    }
  ],
  "data": null
}
```

Tested on the latest master branch of the samples project, which uses 12.0.0-SNAPSHOT

**Comment by snowoutioua** [comment]
Thanks for the quick update. It's really weird. I have an up to date `master` branch of `graphql-annotation` project
```
* 9e25d17 (HEAD -> master, origin/master, origin/HEAD) chore(deps): update dependency org.springframework.boot:org.springframework.boot.gradle.plugin to v2.5.2
* 0a1c221 fix(deps): update dependency graphql-tag to v2.12.5
* 9f7ccd4 chore(deps): update dependency io.projectreactor:reactor-core to v3.4.7
* 6168d55 fix(deps): update dependency graphql to v15.5.1
* 660befc chore(deps): update dependency gradle to v7.1

```
Starting Spring Boot app, requesting from GraphiQL, Trying the argument name as your suggestion but still... Notice that GrapiQL highlight the error in the mutation and also the documentation on the left side specify the `arg0` name.

![image](https://user-images.githubusercontent.com/79160281/124055676-549fbd80-d9f2-11eb-8eab-0629c5795a4e.png)

Trying again with the name `arg0` as the doc suggests but...
![image](https://user-images.githubusercontent.com/79160281/124055864-b06a4680-d9f2-11eb-81b1-9049ec887502.png)

with the same exception.

What do you think I am doing wrong, if we are sure it's not a bug on the latest code?
Thanks

**Comment by BlasiusSecundus** [comment]
I still can't reproduce the issue. Since it is related to the parameter name, I would try to use `@GraphQLName("createPerson")` on that method parameter to explicitly set the name in the GraphQL schema.
