### ISSUE TITLE
no scalar implementation for the named  'XXX' scalar type

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [graphql-java-kickstart/graphql-spring-boot#830]
- dependencies
```
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>12.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>12.0.0</version>
        </dependency>
```

- Schema
```
scalar Long

type Mutation {

}
```

- yml config

```
graphql:
  servlet:
    enabled: true
    cors-enabled: true
    exception-handlers-enabled: true
  playground:
    enabled: false
  voyager:
    enabled: true
  extended-scalars: BigDecimal, Date, Long
```

- errors
```
Caused by: SchemaProblem{errors=[There is no scalar implementation for the named  'Long' scalar type]}
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:82)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:58)
	at org.springframework.graphql.execution.DefaultSchemaResourceGraphQlSourceBuilder.initGraphQlSchema(DefaultSchemaResourceGraphQlSourceBuilder.java:112)
	at org.springframework.graphql.execution.AbstractGraphQlSourceBuilder.build(AbstractGraphQlSourceBuilder.java:85)
	at org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration.graphQlSource(GraphQlAutoConfiguration.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

```

**Comment by BlasiusSecundus** [comment]
I quickly tested on one of my projects, and could not reproduce the issue - the scalar was successfully registered and the schema was created and working correctly.

Could you please share the project? If not, can you please create a minimal project that reproduces the issue?

**Comment by ANUGLYPLUGIN** [comment]
Absolutely ok!
Url: https://github.com/ANUGLYPLUGIN/gqlone

**Comment by ANUGLYPLUGIN** [comment]
My project was just a test project all the time!

**Comment by ZohebMOPO** [comment]
does [this](https://github.com/graphql-java/graphql-java/issues/2134#issuecomment-743715577) helps?
